# Generated by Django 2.1.3 on 2018-11-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='codigo',
        ),
    ]
