# Generated by Django 2.1.3 on 2018-12-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercancia',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
    ]
